# Generated by Django 5.2.7 on 2025-12-14 11:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_pending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cached pending amount for performance', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='party_party_name_117a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['is_active', 'name'], name='party_party_is_acti_23212b_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['-created_at'], name='party_party_created_9341c6_idx'),
        ),
    ]
