# Generated by Django 5.2.7 on 2026-01-15 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('hns_code', models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, unique=True, verbose_name='HNS Code')),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_wholesale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('gst_percent', models.DecimalField(decimal_places=2, help_text='GST %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, help_text='Product image (max 5MB)', null=True, upload_to='item_images/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active items appear in invoice creation forms')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured items appear on dashboard/homepage')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('movement_type', models.CharField(choices=[('retail_sale', 'Retail Sale'), ('wholesale_sale', 'Wholesale Sale'), ('return', 'Return'), ('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged/Lost')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice_id', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='items.item')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'is_deleted', '-is_featured'], name='items_item_is_acti_d218fa_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['hns_code'], name='items_item_hns_cod_ca1b20_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-created_at'], name='items_stock_item_id_d1d65a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='items_stock_movemen_171fba_idx'),
        ),
    ]
