# Generated by Django 5.2.7 on 2026-01-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_created_at_alter_item_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hns_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, unique=True, verbose_name='HNS Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active items appear in invoice creation forms'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured items appear on dashboard/homepage'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('movement_type', models.CharField(choices=[('retail_sale', 'Retail Sale'), ('wholesale_sale', 'Wholesale Sale'), ('return', 'Return'), ('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged/Lost')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice_id', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='items.item')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='items_stock_item_id_d1d65a_idx'), models.Index(fields=['movement_type', '-created_at'], name='items_stock_movemen_171fba_idx')],
            },
        ),
    ]
