# Generated by Django 5.2.7 on 2026-01-15 18:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_mode', models.CharField(choices=[('UNPAID', 'Unpaid'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('ONLINE', 'Online Banking'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='UNPAID', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_invoices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retail Invoice',
                'verbose_name_plural': 'Retail Invoices',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='RetailInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('manual_item_name', models.CharField(blank=True, help_text='Manual item name if not in inventory', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_items', to='retailapp.retailinvoice')),
                ('item', models.ForeignKey(blank=True, help_text='Link to inventory item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetailReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Return amount (auto-calculated if item linked)', max_digits=14)),
                ('reason', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image proof', null=True, upload_to='retail_returns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_returns_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_returns', to='retailapp.retailinvoice')),
                ('item', models.ForeignKey(blank=True, help_text='Link to specific invoice item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailapp.retailinvoiceitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_returns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['-date', '-created_at'], name='retailapp_r_date_b2e232_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['payment_mode'], name='retailapp_r_payment_782b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['is_active', '-date'], name='retailapp_r_is_acti_3e7005_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['customer_mobile', '-date'], name='retailapp_r_custome_edc6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['is_active', 'payment_mode', '-date'], name='retailapp_r_is_acti_d8e3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoice',
            index=models.Index(fields=['date', 'is_active'], name='retailapp_r_date_dfb274_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoiceitem',
            index=models.Index(fields=['invoice', 'is_active'], name='retailapp_r_invoice_a31e08_idx'),
        ),
        migrations.AddIndex(
            model_name='retailinvoiceitem',
            index=models.Index(fields=['item'], name='retailapp_r_item_id_9892c2_idx'),
        ),
        migrations.AddIndex(
            model_name='retailreturn',
            index=models.Index(fields=['invoice', 'is_active'], name='retailapp_r_invoice_ec79df_idx'),
        ),
        migrations.AddIndex(
            model_name='retailreturn',
            index=models.Index(fields=['item'], name='retailapp_r_item_id_6c4e31_idx'),
        ),
        migrations.AddIndex(
            model_name='retailreturn',
            index=models.Index(fields=['-return_date'], name='retailapp_r_return__e0a235_idx'),
        ),
    ]
