# Generated by Django 5.2.7 on 2026-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'verbose_name': 'Retail Invoice', 'verbose_name_plural': 'Retail Invoices'},
        ),
        migrations.RemoveField(
            model_name='retailinvoice',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='retailinvoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='retailinvoice',
            name='payment_mode',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('ONLINE', 'Online Banking'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='UNPAID', help_text='Select payment method (Unpaid or payment mode)', max_length=10),
        ),
        migrations.AddField(
            model_name='retailinvoice',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Transaction ID/Reference number for online payments', max_length=100, null=True),
        ),
    ]
